pipeline {
    agent any
     options {
  buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')
}
    
 triggers {
  pollSCM '0 * * * *'
}
    tools {
        maven 'localmaven'
    }
    stage('Email Notification') {
        steps {
           emailext body: 'Dev job deployed successfully', subject: 'Dev Job', to: 'bhagyashreeshirodkar@gmail.com'
        }
        }
    stages {
        stage('Build maven') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'GIT_Creds', url: 'https://github.com/BhagyashreeBS25/Assignment1.git']]])
                sh 'mvn -f my-app/pom.xml -Dmaven.test.failure.ignore=true clean package'
                
            }
            

            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.jar'
                }
            }
        }
       
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t bhagyshree25/hello-world-1.0 ./my-app'
                }
            }
        }
        
        stage('push docker image'){
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhub_cred', variable: 'dockerhub_creds')]) {
                        sh 'docker login -u bhagyshree25 -p ${dockerhub_creds}'
                        sh 'docker push bhagyshree25/hello-world-1.0'
                    }
                }
            }
        }      
    }
}
